# Generated by Django 5.1 on 2024-08-12 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bank',
            old_name='amount',
            new_name='account_no',
        ),
    ]
